---
title: "R Notebook"
output: html_notebook
---

```{r importandoDados}
library(tidyverse)
library(caret)

dadosBrutos <- read.csv("true_car_listings.csv")
particao <- createDataPartition(dadosBrutos$Price, p = .998, 
                                     list = FALSE, 
                                     times = 1)

dadosDisponiveis <- dadosBrutos[-particao,] %>% 
  select(-Vin)
```


```{r treinandoModelos}
config <- trainControl(method = "cv", number = 5 , verboseIter = TRUE )

linearRegressionModel <- train(Price ~ ., 
                          data = dadosDisponiveis , 
                          method = "lm", 
                          preProcess = c("center","scale"),
                          trControl = config)

knnModel <- train(Price ~ .,
                     data = dadosDisponiveis,
                     method = "knn",
                     preProcess = c("center","scale"),
                     trControl = config)

xgbModel <- train(Price ~ .,
                     data = dadosDisponiveis,
                     method = "xgbLinear",
                     preProcess = c("center","scale"),
                     trControl = config)

id3Model <- train(Price ~ .,
                     data = dadosDisponiveis,
                     method = "rpart",
                     preProcess = c("center","scale"),
                     trControl = config)
```